# -*- coding: utf-8 -*-
"""CoolRoof-India.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7tZsoFPUUROJS1JEnxa-BnLeMYxR55o

# CoolRoof-India
## A Reproducible Geospatial Framework for Mapping Rooftop Albedo Across Indian Cities Using Google's Rooftop Albedo Dataset and H3 Spatial Indexing

**Author:** Jyotiprakash Mirashi

---

### Project Objective

Urban rooftops strongly influence the surface energy balance of cities by controlling the amount of incoming solar radiation reflected back into the atmosphere. Roof albedo is therefore an important indicator for evaluating urban heat mitigation potential and planning cool-roof interventions.

This notebook develops a reproducible geospatial workflow to characterize rooftop albedo across eight major Indian cities using Google's Rooftop Albedo dataset. The workflow integrates administrative boundaries from OpenStreetMap, spatial clipping using GeoPandas, and H3 hierarchical hexagonal indexing to generate standardized city-scale albedo products suitable for comparative urban climate analysis.

### Study Cities

- Ahmedabad
- Bhopal
- Chennai
- Coimbatore
- Kolkata
- Madurai
- Mumbai
- Navi Mumbai

### Main Objectives

1. Import Google's rooftop albedo observations.
2. Perform quality assessment and preprocessing.
3. Retrieve administrative boundaries.
4. Clip rooftop observations for each city.
5. Aggregate observations into H3 hexagons.
6. Compare rooftop albedo across Indian cities.
7. Produce publication-quality figures and datasets.

---
"""

# =============================================================================
# SECTION 01 : PROJECT CONFIGURATION
# =============================================================================

from pathlib import Path

CONFIG = {

    # ----------------------------
    # Data
    # ----------------------------
    "DATA_PATH": "/content/drive/MyDrive/india",

    # ----------------------------
    # Coordinate System
    # ----------------------------
    "CRS": "EPSG:4326",

    # ----------------------------
    # H3
    # ----------------------------
    "H3_RESOLUTION": 9,

    # ----------------------------
    # Visualization
    # ----------------------------
    "COLORMAP": "viridis",
    "FIGSIZE": (22, 12),
    "DPI": 600,

    # ----------------------------
    # Random Seed
    # ----------------------------
    "RANDOM_STATE": 42,

    # ----------------------------
    # Output folders
    # ----------------------------
    "OUTPUT_DIR": Path("outputs"),
    "FIGURE_DIR": Path("outputs/figures"),
    "TABLE_DIR": Path("outputs/tables"),
    "H3_DIR": Path("outputs/h3"),
    "CLIPPED_DIR": Path("outputs/clipped")
}

# Create output folders
for folder in [
    CONFIG["OUTPUT_DIR"],
    CONFIG["FIGURE_DIR"],
    CONFIG["TABLE_DIR"],
    CONFIG["H3_DIR"],
    CONFIG["CLIPPED_DIR"]
]:
    folder.mkdir(parents=True, exist_ok=True)

print("✓ Project configuration loaded")

# =============================================================================
# SECTION 02 : INSTALLATION & LIBRARY IMPORTS
# =============================================================================
#
# Purpose:
# Install (if required) and import all libraries used throughout the project.
# This is the only import cell in the notebook.
#
# =============================================================================

# ----------------------------
# Install Required Packages
# ----------------------------

!pip -q install geopandas pyogrio osmnx h3 contextily mapclassify

# ----------------------------
# Standard Library
# ----------------------------

import os
import warnings
import random
from pathlib import Path

# ----------------------------
# Data Handling
# ----------------------------

import numpy as np
import pandas as pd

# ----------------------------
# Geospatial Analysis
# ----------------------------

import geopandas as gpd
import osmnx as ox
import h3

from shapely.geometry import (
    Point,
    Polygon
)

# ----------------------------
# Visualization
# ----------------------------

import matplotlib.pyplot as plt
import matplotlib as mpl

from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

# Optional (for future basemaps)
import contextily as ctx

# ----------------------------
# Notebook Configuration
# ----------------------------

warnings.filterwarnings("ignore")

random.seed(CONFIG["RANDOM_STATE"])
np.random.seed(CONFIG["RANDOM_STATE"])

# Pandas Display Options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)
pd.set_option("display.precision", 4)

# Matplotlib Defaults
plt.style.use("default")

plt.rcParams.update({

    "figure.figsize": CONFIG["FIGSIZE"],

    "figure.dpi": CONFIG["DPI"],

    "font.family": "DejaVu Sans",

    "font.size": 11,

    "axes.titlesize": 14,

    "axes.labelsize": 12,

    "axes.titleweight": "bold",

    "figure.titleweight": "bold",

    "savefig.dpi": CONFIG["DPI"],

    "savefig.bbox": "tight"

})

print("="*70)
print(" CoolRoof-India Environment Successfully Initialized")
print("="*70)

print(f"GeoPandas : {gpd.__version__}")
print(f"Pandas    : {pd.__version__}")
print(f"OSMnx     : {ox.__version__}")
print(f"H3        : {h3.__version__}")

print("="*70)

from google.colab import drive

drive.mount("/content/drive")

print("✓ Google Drive successfully mounted.")

# =============================================================================
# SECTION 03 : LOAD AND VALIDATE GOOGLE ROOFTOP ALBEDO DATASET
# =============================================================================
#
# Purpose
# -------
# Load Google's rooftop albedo dataset and perform automated quality
# assessment before any spatial processing.
#
# Inputs
# ------
# CONFIG["DATA_PATH"]
#
# Outputs
# -------
# roof_df : pandas.DataFrame
#
# =============================================================================

# ----------------------------
# Load Dataset
# ----------------------------

print("Loading Google Rooftop Albedo dataset...")

roof_df = pd.read_csv(CONFIG["DATA_PATH"])

print("✓ Dataset successfully loaded.")

# ----------------------------
# Basic Information
# ----------------------------

print("\n" + "="*70)
print("DATASET OVERVIEW")
print("="*70)

print(f"Rows               : {roof_df.shape[0]:,}")
print(f"Columns            : {roof_df.shape[1]}")

print("\nColumn Names")
print(list(roof_df.columns))

# ----------------------------
# Validate Required Columns
# ----------------------------

required_columns = [
    "mean_albedo",
    "lat",
    "lng"
]

missing_columns = [
    col
    for col in required_columns
    if col not in roof_df.columns
]

assert len(missing_columns) == 0, \
    f"Missing required columns: {missing_columns}"

print("\n✓ Required columns verified.")

# ----------------------------
# Missing Values
# ----------------------------

print("\nMissing Values")

display(
    roof_df.isna().sum().to_frame(
        "Missing Count"
    )
)

# ----------------------------
# Duplicate Records
# ----------------------------

duplicates = roof_df.duplicated().sum()

print(f"\nDuplicate Records : {duplicates:,}")

# ----------------------------
# Summary Statistics
# ----------------------------

print("\nNumerical Summary")

display(
    roof_df.describe().T
)

print("\n✓ Data quality assessment completed.")

# =============================================================================
# SECTION 04 : DATA QUALITY ASSESSMENT & CLEANING
# =============================================================================
#
# Purpose
# -------
# Perform automated quality assessment and remove invalid observations
# before geospatial analysis.
#
# Inputs
# ------
# roof_df
#
# Outputs
# -------
# roof_df (cleaned)
# quality_report (dictionary)
#
# =============================================================================

print("=" * 80)
print("DATA QUALITY ASSESSMENT")
print("=" * 80)

# -------------------------------------------------------------------------
# Initial Record Count
# -------------------------------------------------------------------------

initial_records = len(roof_df)

# -------------------------------------------------------------------------
# Remove Missing Values
# -------------------------------------------------------------------------

roof_df = roof_df.dropna(
    subset=["mean_albedo", "lat", "lng"]
)

# -------------------------------------------------------------------------
# Remove Duplicate Records
# -------------------------------------------------------------------------

roof_df = roof_df.drop_duplicates()

# -------------------------------------------------------------------------
# Remove Invalid Coordinates
# -------------------------------------------------------------------------

roof_df = roof_df[
    roof_df["lat"].between(-90, 90)
]

roof_df = roof_df[
    roof_df["lng"].between(-180, 180)
]

# -------------------------------------------------------------------------
# Remove Invalid Albedo Values
# -------------------------------------------------------------------------

roof_df = roof_df[
    roof_df["mean_albedo"].between(0, 1)
]

# -------------------------------------------------------------------------
# Reset Index
# -------------------------------------------------------------------------

roof_df = roof_df.reset_index(drop=True)

# -------------------------------------------------------------------------
# Final Record Count
# -------------------------------------------------------------------------

final_records = len(roof_df)

removed_records = initial_records - final_records

# -------------------------------------------------------------------------
# Dataset Extent
# -------------------------------------------------------------------------

quality_report = {

    "Initial Records": initial_records,

    "Final Records": final_records,

    "Removed Records": removed_records,

    "Latitude Range":
        (
            roof_df["lat"].min(),
            roof_df["lat"].max()
        ),

    "Longitude Range":
        (
            roof_df["lng"].min(),
            roof_df["lng"].max()
        ),

    "Minimum Albedo":
        roof_df["mean_albedo"].min(),

    "Maximum Albedo":
        roof_df["mean_albedo"].max(),

    "Mean Albedo":
        roof_df["mean_albedo"].mean(),

    "Median Albedo":
        roof_df["mean_albedo"].median(),

    "Standard Deviation":
        roof_df["mean_albedo"].std()

}

# -------------------------------------------------------------------------
# Print Report
# -------------------------------------------------------------------------

print("\nQUALITY REPORT\n")

for key, value in quality_report.items():

    print(f"{key:<25} : {value}")

print("\n✓ Dataset successfully cleaned.")

# =============================================================================
# SECTION 05 : CREATE GEOSPATIAL DATAFRAME
# =============================================================================
#
# Purpose
# -------
# Convert the cleaned rooftop dataset into a GeoDataFrame using
# geographic coordinates (WGS84).
#
# Inputs
# ------
# roof_df
#
# Outputs
# -------
# roof_gdf
#
# =============================================================================

print("=" * 80)
print("CREATING GEOSPATIAL DATAFRAME")
print("=" * 80)

# -------------------------------------------------------------------------
# Create Geometry
# -------------------------------------------------------------------------

roof_gdf = gpd.GeoDataFrame(
    roof_df,
    geometry=gpd.points_from_xy(
        roof_df["lng"],
        roof_df["lat"]
    ),
    crs=CONFIG["CRS"]
)

# -------------------------------------------------------------------------
# Validate CRS
# -------------------------------------------------------------------------

assert roof_gdf.crs == CONFIG["CRS"], \
    "Coordinate Reference System (CRS) mismatch."

# -------------------------------------------------------------------------
# Spatial Extent
# -------------------------------------------------------------------------

xmin, ymin, xmax, ymax = roof_gdf.total_bounds

print(f"Coordinate Reference System : {roof_gdf.crs}")
print(f"Spatial Extent")
print(f"   West  : {xmin:.4f}")
print(f"   South : {ymin:.4f}")
print(f"   East  : {xmax:.4f}")
print(f"   North : {ymax:.4f}")

print(f"\nTotal Rooftop Observations : {len(roof_gdf):,}")

print("\n✓ GeoDataFrame successfully created.")

# =============================================================================
# SECTION 06 : SPATIAL VALIDATION
# =============================================================================

fig, ax = plt.subplots(figsize=(10, 8))

roof_gdf.plot(
    ax=ax,
    markersize=0.08,
    color="#2C7FB8",
    alpha=0.60
)

ax.set_title(
    "Spatial Distribution of Google Rooftop Albedo Observations",
    fontsize=18,
    fontweight="bold",
    pad=15
)

ax.set_xlabel("Longitude", fontsize=12)
ax.set_ylabel("Latitude", fontsize=12)

ax.grid(
    linestyle="--",
    alpha=0.30
)

plt.tight_layout()

plt.show()

# =============================================================================
# SECTION 06 : STUDY AREA DEFINITION
# =============================================================================
#
# Purpose
# -------
# Define the study cities and their OpenStreetMap geocoding queries.
#
# Outputs
# -------
# study_area_df
#
# =============================================================================

study_area_df = pd.DataFrame({

    "City": [
        "Ahmedabad",
        "Bhopal",
        "Chennai",
        "Coimbatore",
        "Kolkata",
        "Madurai",
        "Mumbai",
        "Navi Mumbai"
    ],

    "State": [
        "Gujarat",
        "Madhya Pradesh",
        "Tamil Nadu",
        "Tamil Nadu",
        "West Bengal",
        "Tamil Nadu",
        "Maharashtra",
        "Maharashtra"
    ],

    "Country": [
        "India"
    ] * 8,

    "OSM_Query": [

        "Ahmedabad, Gujarat, India",

        "Bhopal, Madhya Pradesh, India",

        "Chennai, Tamil Nadu, India",

        "Coimbatore, Tamil Nadu, India",

        "Kolkata, West Bengal, India",

        "Madurai, Tamil Nadu, India",

        "Mumbai Suburban, Maharashtra, India",

        "Navi Mumbai, Maharashtra, India"

    ],

    "Which_Result": [
        None,
        None,
        None,
        None,
        None,
        None,
        1,
        None
    ]

})

display(study_area_df)

print(f"\n✓ {len(study_area_df)} study cities defined.")

# =============================================================================
# SECTION 07 : DOWNLOAD ADMINISTRATIVE BOUNDARIES
# =============================================================================

print("=" * 80)
print("DOWNLOADING CITY BOUNDARIES")
print("=" * 80)

boundary_list = []

for _, row in study_area_df.iterrows():

    print(f"Downloading {row.City}...")

    if pd.isna(row.Which_Result):

        boundary = ox.geocode_to_gdf(
            row.OSM_Query
        )

    else:

        boundary = ox.geocode_to_gdf(
            row.OSM_Query,
            which_result=int(row.Which_Result)
        )

    boundary["City"] = row.City
    boundary["State"] = row.State

    boundary_list.append(
        boundary[
            ["City", "State", "geometry"]
        ]
    )

city_boundaries_gdf = pd.concat(
    boundary_list,
    ignore_index=True
)

city_boundaries_gdf = gpd.GeoDataFrame(
    city_boundaries_gdf,
    crs=CONFIG["CRS"]
)

print("\n✓ All administrative boundaries downloaded successfully.")

# =============================================================================
# SECTION 08 : VALIDATE STUDY AREA
# =============================================================================

fig, ax = plt.subplots(figsize=(10,10))

city_boundaries_gdf.boundary.plot(
    ax=ax,
    linewidth=2,
    edgecolor="#0F4C81"
)

for _, row in city_boundaries_gdf.iterrows():

    centroid = row.geometry.centroid

    ax.text(
        centroid.x,
        centroid.y,
        row.City,
        fontsize=10,
        ha="center"
    )

ax.set_title(
    "Administrative Boundaries of the Study Cities",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout()

plt.show()

# =============================================================================
# SECTION 09 : CLIP ROOFTOP OBSERVATIONS
# =============================================================================
#
# Purpose
# -------
# Clip rooftop observations to each study city's administrative boundary.
#
# Inputs
# ------
# roof_gdf
# city_boundaries_gdf
#
# Outputs
# -------
# city_points (dictionary)
# clipping_summary_df
#
# =============================================================================

def clip_rooftop_points(roof_gdf, city_boundaries_gdf):
    """
    Clip rooftop observations to administrative city boundaries.

    Parameters
    ----------
    roof_gdf : GeoDataFrame
        Google rooftop observations.

    city_boundaries_gdf : GeoDataFrame
        Administrative city boundaries.

    Returns
    -------
    city_points : dict
        Dictionary containing clipped GeoDataFrames.

    clipping_summary_df : pandas.DataFrame
        Summary statistics for clipping operation.
    """

    city_points = {}

    clipping_summary = []

    for _, row in city_boundaries_gdf.iterrows():

        city = row["City"]

        print(f"Processing {city}...")

        boundary = gpd.GeoDataFrame(
            [row],
            crs=city_boundaries_gdf.crs
        )

        clipped = gpd.clip(
            roof_gdf,
            boundary
        )

        city_points[city] = clipped

        clipping_summary.append({

            "City": city,

            "Roof_Observations": len(clipped),

            "Mean_Albedo": clipped["mean_albedo"].mean(),

            "Minimum_Albedo": clipped["mean_albedo"].min(),

            "Maximum_Albedo": clipped["mean_albedo"].max()

        })

    clipping_summary_df = pd.DataFrame(
        clipping_summary
    )

    return city_points, clipping_summary_df

# =============================================================================
# EXECUTE CLIPPING
# =============================================================================

city_points, clipping_summary_df = clip_rooftop_points(
    roof_gdf,
    city_boundaries_gdf
)

print("\n✓ Rooftop observations clipped successfully.")

display(clipping_summary_df)

# =============================================================================
# VISUAL VALIDATION OF CLIPPED DATA
# =============================================================================

fig, axes = plt.subplots(
    2,
    4,
    figsize=(18,10)
)

axes = axes.flatten()

for ax, city in zip(axes, city_points.keys()):

    city_points[city].plot(
        ax=ax,
        markersize=0.08,
        color="#1f77b4",
        alpha=0.50
    )

    ax.set_title(
        city,
        fontsize=12,
        fontweight="bold"
    )

    ax.set_axis_off()

plt.suptitle(
    "Clipped Rooftop Observations",
    fontsize=18,
    fontweight="bold"
)

plt.tight_layout()

plt.show()

# =============================================================================
# SECTION 10 : H3 SPATIAL AGGREGATION
# =============================================================================
#
# Purpose
# -------
# Aggregate rooftop observations into H3 hexagonal cells.
#
# =============================================================================

def h3_to_polygon(cell):
    """
    Convert an H3 cell to a Shapely Polygon.
    """

    boundary = h3.cell_to_boundary(cell)

    return Polygon(
        [(lng, lat) for lat, lng in boundary]
    )


def aggregate_city_to_h3(city_gdf, resolution):
    """
    Aggregate rooftop observations into H3 hexagons.
    """

    data = city_gdf.copy()

    # Assign H3 Index
    data["H3_Cell"] = data.apply(
        lambda row: h3.latlng_to_cell(
            row.lat,
            row.lng,
            resolution
        ),
        axis=1
    )

    # Aggregate Statistics
    hex_df = (
        data
        .groupby("H3_Cell")
        .agg(
            Mean_Albedo=("mean_albedo", "mean"),
            Median_Albedo=("mean_albedo", "median"),
            Std_Albedo=("mean_albedo", "std"),
            Roof_Count=("mean_albedo", "count")
        )
        .reset_index()
    )

    # Convert H3 to Polygon
    hex_df["geometry"] = hex_df["H3_Cell"].apply(
        h3_to_polygon
    )

    return gpd.GeoDataFrame(
        hex_df,
        geometry="geometry",
        crs=CONFIG["CRS"]
    )

# =============================================================================
# AGGREGATE ALL STUDY CITIES
# =============================================================================

city_hexagons = {}

hexagon_summary = []

for city, data in city_points.items():

    print(f"Aggregating {city}...")

    hex_gdf = aggregate_city_to_h3(
        data,
        CONFIG["H3_RESOLUTION"]
    )

    city_hexagons[city] = hex_gdf

    hexagon_summary.append({

        "City": city,

        "Hexagons": len(hex_gdf),

        "Mean Albedo":
            hex_gdf["Mean_Albedo"].mean(),

        "Mean Roofs / Hex":
            hex_gdf["Roof_Count"].mean()

    })

print("\n✓ H3 aggregation completed.")

# =============================================================================
# H3 SUMMARY
# =============================================================================

hexagon_summary_df = pd.DataFrame(
    hexagon_summary
)

display(
    hexagon_summary_df
)

# =============================================================================
# EXPORT H3 DATASETS
# =============================================================================

for city, hex_gdf in city_hexagons.items():

    output = (
        CONFIG["H3_DIR"] /
        f"{city.replace(' ', '_')}.geojson"
    )

    hex_gdf.to_file(
        output,
        driver="GeoJSON"
    )

print("✓ H3 layers exported.")

# =============================================================================
# SECTION 11 : CITY-LEVEL STATISTICS
# =============================================================================
#
# Purpose
# -------
# Compute descriptive statistics for rooftop albedo across all study cities.
#
# Outputs
# -------
# city_statistics_df
#
# =============================================================================

city_statistics = []

for city, hex_gdf in city_hexagons.items():

    city_statistics.append({

        "City": city,

        "Number of Roofs":
            city_points[city].shape[0],

        "Number of H3 Cells":
            hex_gdf.shape[0],

        "Mean Albedo":
            city_points[city]["mean_albedo"].mean(),

        "Median Albedo":
            city_points[city]["mean_albedo"].median(),

        "Minimum Albedo":
            city_points[city]["mean_albedo"].min(),

        "Maximum Albedo":
            city_points[city]["mean_albedo"].max(),

        "Standard Deviation":
            city_points[city]["mean_albedo"].std(),

        "Q25":
            city_points[city]["mean_albedo"].quantile(0.25),

        "Q75":
            city_points[city]["mean_albedo"].quantile(0.75)

    })

city_statistics_df = pd.DataFrame(city_statistics)

city_statistics_df

# =============================================================================
# SECTION 12 : COOL ROOF INDICATORS
# =============================================================================

city_statistics_df["Low Albedo (<0.20)"] = [

    (city_points[city]["mean_albedo"] < 0.20).mean()*100

    for city in city_statistics_df["City"]

]

city_statistics_df["Moderate (0.20-0.30)"] = [

    city_points[city]["mean_albedo"].between(
        0.20,
        0.30
    ).mean()*100

    for city in city_statistics_df["City"]

]

city_statistics_df["High Albedo (>0.30)"] = [

    (city_points[city]["mean_albedo"] > 0.30).mean()*100

    for city in city_statistics_df["City"]

]

city_statistics_df.round(2)

# =============================================================================
# SECTION 13 : CITY RANKING
# =============================================================================

ranking = city_statistics_df.sort_values(

    "Mean Albedo",

    ascending=False

).reset_index(drop=True)

ranking.insert(

    0,

    "Rank",

    range(1, len(ranking)+1)

)

display(ranking)

# =============================================================================
# EXPORT STATISTICS
# =============================================================================

output = (

    CONFIG["TABLE_DIR"] /

    "City_Statistics.csv"

)

city_statistics_df.to_csv(

    output,

    index=False

)

print("✓ Statistics exported.")

# =============================================================================
# MULTI-CITY H3 VISUALIZATION
# =============================================================================

def plot_all_cities(city_hexagons):

    fig, axes = plt.subplots(
        2,
        4,
        figsize=(24,12)
    )

    axes = axes.flatten()

    # ----------------------------------------------------
    # Global Color Scale
    # ----------------------------------------------------

    vmin = min(

        gdf["Mean_Albedo"].min()

        for gdf in city_hexagons.values()

    )

    vmax = max(

        gdf["Mean_Albedo"].max()

        for gdf in city_hexagons.values()

    )

    norm = Normalize(
        vmin=vmin,
        vmax=vmax
    )

    # ----------------------------------------------------
    # Plot Cities
    # ----------------------------------------------------

    for ax, city in zip(

        axes,

        city_hexagons.keys()

    ):

        gdf = city_hexagons[city]

        gdf.plot(

            ax=ax,

            column="Mean_Albedo",

            cmap=CONFIG["COLORMAP"],

            edgecolor="white",

            linewidth=0.02,

            legend=False,

            vmin=vmin,

            vmax=vmax

        )

        xmin, ymin, xmax, ymax = gdf.total_bounds

        ax.set_xlim(xmin, xmax)

        ax.set_ylim(ymin, ymax)

        ax.set_title(

            city,

            fontsize=14,

            fontweight="bold"

        )

        ax.set_axis_off()

    # ----------------------------------------------------
    # Colorbar
    # ----------------------------------------------------

    sm = ScalarMappable(

        norm=norm,

        cmap=CONFIG["COLORMAP"]

    )

    sm.set_array([])

    cbar = fig.colorbar(

        sm,

        ax=axes,

        location="right",

        fraction=0.025,

        pad=0.02

    )

    cbar.set_label(

        "Mean Rooftop Albedo",

        fontsize=12,

        fontweight="bold"

    )

    fig.suptitle(

        "Spatial Distribution of Rooftop Albedo Across Indian Cities",

        fontsize=22,

        fontweight="bold"

    )

    plt.savefig(

        CONFIG["FIGURE_DIR"] /

        "Figure_04_H3_Maps.png",

        dpi=CONFIG["DPI"],

        bbox_inches="tight"

    )

    plt.show()

# =============================================================================
# GENERATE FIGURE 4
# =============================================================================

plot_all_cities(city_hexagons)

# =============================================================================
# SECTION 15 : FIGURE 5 - CITY RANKING
# =============================================================================

ranking = city_statistics_df.sort_values(
    "Mean Albedo",
    ascending=True
)

fig, ax = plt.subplots(figsize=(10,6))

bars = ax.barh(

    ranking["City"],

    ranking["Mean Albedo"],

    color=plt.cm.viridis(
        np.linspace(
            0.2,
            0.9,
            len(ranking)
        )
    )

)

# Labels

for bar in bars:

    width = bar.get_width()

    ax.text(

        width + 0.002,

        bar.get_y() + bar.get_height()/2,

        f"{width:.3f}",

        va="center",

        fontsize=10

    )

ax.set_xlabel("Mean Rooftop Albedo")

ax.set_ylabel("")

ax.set_title(

    "Mean Rooftop Albedo by City",

    fontsize=18,

    fontweight="bold"

)

plt.grid(

    axis="x",

    alpha=0.3

)

plt.savefig(

    CONFIG["FIGURE_DIR"] /

    "Figure_05_City_Ranking.png",

    dpi=CONFIG["DPI"]

)

plt.show()

# =============================================================================
# FIGURE 6 : BOXPLOT
# =============================================================================

plot_data = [

    city_points[city]["mean_albedo"]

    for city in city_points

]

fig, ax = plt.subplots(figsize=(12,6))

ax.boxplot(

    plot_data,

    labels=city_points.keys(),

    patch_artist=True

)

ax.set_ylabel("Roof Albedo")

ax.set_title(

    "Distribution of Rooftop Albedo Across Cities",

    fontsize=18,

    fontweight="bold"

)

plt.xticks(rotation=20)

plt.grid(

    axis="y",

    alpha=0.3

)

plt.savefig(

    CONFIG["FIGURE_DIR"] /

    "Figure_06_Boxplot.png",

    dpi=CONFIG["DPI"]

)

plt.show()

# =============================================================================
# FIGURE 7 : HISTOGRAMS
# =============================================================================

fig, axes = plt.subplots(

    2,

    4,

    figsize=(18,10)

)

axes = axes.flatten()

for ax, city in zip(

    axes,

    city_points.keys()

):

    ax.hist(

        city_points[city]["mean_albedo"],

        bins=30,

        color="#2C7FB8",

        edgecolor="black",

        alpha=0.8

    )

    ax.set_title(city)

plt.tight_layout()

plt.savefig(

    CONFIG["FIGURE_DIR"] /

    "Figure_07_Histograms.png",

    dpi=CONFIG["DPI"]

)

plt.show()